FROM alpine:3.14
RUN  apk update \
  && apk upgrade \
  && apk add --update openjdk11 tzdata curl unzip bash \
  && rm -rf /var/cache/apk/*

COPY target/finmanapi-0.0.1.jar finmanapi-0.0.1.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/finmanapi-0.0.1.jar"