spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fintracker
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: pg1
    hibernate:
      ddl-auto: create-drop
    show-sql: true

